#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use MyApp\Command\MyCommand;

$application = new Application('echo', '1.0.0');
$command = new MyCommand();

$application->add($command);

$application->setDefaultCommand($command->getName(), true);
$application->run();